import {
  ClerkProvider
} from '@clerk/nextjs';


import { neobrutalism } from '@clerk/themes'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
      <html lang="en">
        <body className={'w-screen h-dvh relative flex items-center justify-center bg-dark-background-color text-dark-primary-text'}>
          
        <ClerkProvider
          appearance={{
            baseTheme: neobrutalism
          }}
        >
          {children}
        </ClerkProvider>
        </body>
      </html>
    
  );
}

