import {
  ClerkProvider
} from '@clerk/nextjs';


import { neobrutalism } from '@clerk/themes'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { check } from 'drizzle-orm/mysql-core';
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
      <html lang="en">
        <body className={'w-screen h-dvh bg-darkest relative flex items-center justify-center'}>
          
        <ClerkProvider
          appearance={{
            baseTheme: neobrutalism
          }}
        >
          {children}
          {/* {'This is a ' + ( checkUserExist ? 'old user.' : 'new user.') }
          {user?.firstName + ' ' + user?.lastName}
          <SignOutButton>
            <button className='bg-blue-600 rounded-xl p-2'>Sign Out</button>
          </SignOutButton> */}
        </ClerkProvider>
        </body>
      </html>
    
  );
}

