import { ClerkProvider } from '@clerk/nextjs';

import { neobrutalism } from '@clerk/themes';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={'bg-light-surface-0 text-light-text-1 text-sm'}>
                <ClerkProvider
                    appearance={{
                        baseTheme: neobrutalism
                    }}
                >
                    {children}
                </ClerkProvider>
            </body>
        </html>
    );
}
